# buildspec.yml for PipelineForge
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing Python dependencies
      - pip install -r app/requirements.txt
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      - ECR_REGISTRY=$(echo $ECR_REPO | cut -d/ -f1)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $ECR_REPO:$IMAGE_TAG ./app
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:latest

artifacts:
  files:
    - cloudformation/**/*
