AWSTemplateFormatVersion: '2010-09-09'
Description: PipelineForge CodeArtifact Domain and Repository

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name (e.g., dev, prod)

Resources:
  CodeArtifactDomain:
    Type: AWS::CodeArtifact::Domain
    Properties:
      DomainName: !Sub '${EnvironmentName}-pipelineforge-domain'

  CodeArtifactRepository:
    Type: AWS::CodeArtifact::Repository
    DependsOn: CodeArtifactDomain
    Properties:
      RepositoryName: !Sub '${EnvironmentName}-pipelineforge-repo'
      DomainName: !Sub '${EnvironmentName}-pipelineforge-domain'
      Description: PipelineForge artifact repository

Outputs:
  CodeArtifactDomainName:
    Description: CodeArtifact Domain Name
    Value: !Sub '${EnvironmentName}-pipelineforge-domain'
    Export:
      Name: !Sub '${EnvironmentName}-CodeArtifactDomainName'
  CodeArtifactRepositoryName:
    Description: CodeArtifact Repository Name
    Value: !Sub '${EnvironmentName}-pipelineforge-repo'
    Export:
      Name: !Sub '${EnvironmentName}-CodeArtifactRepositoryName'
